import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, expect, it, vi } from 'vitest'
import { ImageComparison, ModelExplorer } from './ImageLab'

const api = vi.hoisted(() => ({ createJob: vi.fn(), getJob: vi.fn(), fetchResult: vi.fn(), cancelJob: vi.fn() }))
vi.mock('./api', () => api)
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals() })

it('uploads only a crop and reuses its completed preview when switching back', async () => {
  const drawImage = vi.fn()
  vi.stubGlobal('createImageBitmap', vi.fn().mockResolvedValue({ width: 1000, height: 800, close: vi.fn() }))
  vi.spyOn(HTMLCanvasElement.prototype, 'getContext').mockReturnValue({ drawImage } as unknown as CanvasRenderingContext2D)
  vi.spyOn(HTMLCanvasElement.prototype, 'toBlob').mockImplementation(callback => callback(new Blob(['crop'], { type: 'image/png' })))
  vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:preview')
  vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => {})
  api.createJob.mockResolvedValue({ jobId: 'preview', token: 'secret', expiresAt: '2099-01-01' })
  api.getJob.mockResolvedValue({ status: 'succeeded' })
  api.fetchResult.mockResolvedValue(new Blob(['result']))
  api.cancelJob.mockResolvedValue(undefined)
  const file = new File(['full-image'], 'photo.png')
  const props = { file, model: 'standard', scale: 2, strength: 100, language: 'ru' as const }
  const { rerender } = render(<ModelExplorer {...props} />)
  fireEvent.click(screen.getByRole('button', { name: 'Проба выбранного режима' }))
  await waitFor(() => expect(screen.getByRole('button', { name: /Готово за/ })).toBeDisabled())
  expect(api.createJob).toHaveBeenCalledOnce()
  expect(api.createJob.mock.calls[0][1][0].size).toBe(4)
  expect(drawImage.mock.calls[0].slice(1)).toEqual([420, 320, 160, 160, 0, 0, 160, 160])
  rerender(<ModelExplorer {...props} model="detail" />)
  expect(screen.getByRole('button', { name: 'Проба выбранного режима' })).toBeEnabled()
  rerender(<ModelExplorer {...props} />)
  expect(screen.getByRole('button', { name: /Готово за/ })).toBeDisabled()
  expect(api.createJob).toHaveBeenCalledOnce()
  rerender(<ModelExplorer {...props} faceRestoration={100} />)
  fireEvent.click(screen.getByRole('button', { name: 'Проба выбранного режима' }))
  await waitFor(() => expect(api.createJob).toHaveBeenCalledTimes(2))
  expect(drawImage.mock.calls[1].slice(1)).toEqual([0, 0, 1000, 800, 0, 0, 256, 205])
  expect(api.createJob.mock.calls[1][2]).toMatchObject({ faceRestoration: 100 })
  await waitFor(() => expect(api.cancelJob).toHaveBeenCalled())
})

it('isolates original and result, including transparent result areas and full-image views', () => {
  const { rerender } = render(<ImageComparison before="blob:original" after="blob:transparent-result" language="ru" />)
  const original = screen.getByRole('img', { name: 'До' })
  const result = screen.getByRole('img', { name: 'После' })
  expect(original).toHaveAttribute('src', 'blob:original')
  expect(result).toHaveAttribute('src', 'blob:transparent-result')
  expect(original.parentElement).toHaveStyle({ clipPath: 'inset(0 50% 0 0)' })
  expect(result.parentElement).toHaveStyle({ clipPath: 'inset(0 0 0 50%)' })
  fireEvent.click(screen.getByRole('button', { name: 'Только после' }))
  expect(original.parentElement).toHaveStyle({ clipPath: 'inset(0 100% 0 0)' })
  expect(result.parentElement).toHaveStyle({ clipPath: 'inset(0 0 0 0%)' })
  fireEvent.click(screen.getByRole('button', { name: 'Только до' }))
  expect(result.parentElement).toHaveStyle({ clipPath: 'inset(0 0 0 100%)' })
  fireEvent.change(screen.getByRole('combobox'), { target: { value: '2' } })
  expect(original).toHaveStyle({ transform: 'translate(0px, 0px) scale(2)' })
  expect(result).toHaveStyle({ transform: 'translate(0px, 0px) scale(2)' })
  rerender(<ImageComparison before="blob:original" after="blob:new-result" language="ru" />)
  expect(screen.getByRole('slider')).toHaveValue('50')
})
